name = "adviceapp-database"
main = "src/index.mjs"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "adviceapp-database"
database_id = "3ff9e850-b57f-46dd-a861-01fa88d49d79"

[vars]
GOOGLE_CLIENT_ID = "79096511971-4bltkc93o1o82nm13guve8gp1lt0cs0n.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI ="https://adviceapp-database.nelson-ec5.workers.dev/api/auth/google/callback"
JWT_SECRET = "LwMFqUWPurvJKrAbDpFHrBdbTUpZkkcHQLqDmgenWLQDu"